using System;
using UnityEngine;

public class Level1PlayerBullet : MonoBehaviour
{
    [SerializeField] private float moveSpeed = 25f;
    [SerializeField] private float timeDestroy = 0.5f;
    [SerializeField] private float damage = 10f;
    void Start()
    {
        Destroy(gameObject, timeDestroy);
    }

    // Update is called once per frame
    void Update()
    {
        MoveBullet();
    }

    void MoveBullet()
    {
        transform.Translate(Vector2.right * moveSpeed * Time.deltaTime);
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.CompareTag("Enemy"))
        {
            Level1Enemy level1Enemy = collision.GetComponent<Level1Enemy>();
            if (level1Enemy != null)
            {
                level1Enemy.TakeDamage(damage);
            }
            Destroy(gameObject);
        }
    }
}
